development:
  adapter: postgresql
  encoding: unicode
  database: app_ocapi_development
  pool: 5
  host: localhost
  username: cefs1984

test:
  adapter: postgresql
  encoding: unicode
  database: app_ocapi_test
  pool: 5
  host: localhost
  username: cefs1984
