require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdvertisingsController do

  # This should return the minimal set of attributes required to create a valid
  # Advertising. As you add validations to Advertising, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdvertisingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all advertisings as @advertisings" do
      advertising = Advertising.create! valid_attributes
      get :index, {}, valid_session
      assigns(:advertisings).should eq([advertising])
    end
  end

  describe "GET show" do
    it "assigns the requested advertising as @advertising" do
      advertising = Advertising.create! valid_attributes
      get :show, {:id => advertising.to_param}, valid_session
      assigns(:advertising).should eq(advertising)
    end
  end

  describe "GET new" do
    it "assigns a new advertising as @advertising" do
      get :new, {}, valid_session
      assigns(:advertising).should be_a_new(Advertising)
    end
  end

  describe "GET edit" do
    it "assigns the requested advertising as @advertising" do
      advertising = Advertising.create! valid_attributes
      get :edit, {:id => advertising.to_param}, valid_session
      assigns(:advertising).should eq(advertising)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Advertising" do
        expect {
          post :create, {:advertising => valid_attributes}, valid_session
        }.to change(Advertising, :count).by(1)
      end

      it "assigns a newly created advertising as @advertising" do
        post :create, {:advertising => valid_attributes}, valid_session
        assigns(:advertising).should be_a(Advertising)
        assigns(:advertising).should be_persisted
      end

      it "redirects to the created advertising" do
        post :create, {:advertising => valid_attributes}, valid_session
        response.should redirect_to(Advertising.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved advertising as @advertising" do
        # Trigger the behavior that occurs when invalid params are submitted
        Advertising.any_instance.stub(:save).and_return(false)
        post :create, {:advertising => { "title" => "invalid value" }}, valid_session
        assigns(:advertising).should be_a_new(Advertising)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Advertising.any_instance.stub(:save).and_return(false)
        post :create, {:advertising => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested advertising" do
        advertising = Advertising.create! valid_attributes
        # Assuming there are no other advertisings in the database, this
        # specifies that the Advertising created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Advertising.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => advertising.to_param, :advertising => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested advertising as @advertising" do
        advertising = Advertising.create! valid_attributes
        put :update, {:id => advertising.to_param, :advertising => valid_attributes}, valid_session
        assigns(:advertising).should eq(advertising)
      end

      it "redirects to the advertising" do
        advertising = Advertising.create! valid_attributes
        put :update, {:id => advertising.to_param, :advertising => valid_attributes}, valid_session
        response.should redirect_to(advertising)
      end
    end

    describe "with invalid params" do
      it "assigns the advertising as @advertising" do
        advertising = Advertising.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Advertising.any_instance.stub(:save).and_return(false)
        put :update, {:id => advertising.to_param, :advertising => { "title" => "invalid value" }}, valid_session
        assigns(:advertising).should eq(advertising)
      end

      it "re-renders the 'edit' template" do
        advertising = Advertising.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Advertising.any_instance.stub(:save).and_return(false)
        put :update, {:id => advertising.to_param, :advertising => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested advertising" do
      advertising = Advertising.create! valid_attributes
      expect {
        delete :destroy, {:id => advertising.to_param}, valid_session
      }.to change(Advertising, :count).by(-1)
    end

    it "redirects to the advertisings list" do
      advertising = Advertising.create! valid_attributes
      delete :destroy, {:id => advertising.to_param}, valid_session
      response.should redirect_to(advertisings_url)
    end
  end

end
